const titles = [
	"➤ |",
	"➤ ",
	"➤ |",
	"➤ ",
	"➤ |",
	"➤ D|",
	"➤ De|",
	"➤ DeA|",
	"➤ DeAn|",
	"➤ DeAng|",
	"➤ DeAnge|",
	"➤ DeAngel|",
	"➤ DeAngelo|",
	"➤ DeAngelo'|",
	"➤ DeAngelo's|",
	"➤ DeAngelo's |",
	"➤ DeAngelo's P|",
	"➤ DeAngelo's Po|",
	"➤ DeAngelo's Por|",
	"➤ DeAngelo's Port|",
	"➤ DeAngelo's Portf|",
	"➤ DeAngelo's Portfo|",
	"➤ DeAngelo's Portfol|",
	"➤ DeAngelo's Portfoli|",
	"➤ DeAngelo's Portfolio|",
	"➤ DeAngelo's Portfolio",
	"➤ DeAngelo's Portfolio [⏎]",
	"➤ DeAngelo's Portfolio [⏎]",
	"➤ DeAngelo's Portfolio [⌫]",
	"➤ DeAngelo's Portfolio [⌫]",
	"➤ DeAngelo's Portfol [⌫]",
	"➤ DeAngelo's Portfo [⌫]",
	"➤ DeAngelo's Portf [⌫]",
	"➤ DeAngelo's Port [⌫]",
	"➤ DeAngelo's Por [⌫]",
	"➤ DeAngelo's Po [⌫]",
	"➤ DeAngelo's P [⌫]",
	"➤ DeAngelo's  [⌫]",
	"➤ DeAngelo' [⌫]",
	"➤ DeAngelo [⌫]",
	"➤ DeAngel [⌫]",
	"➤ DeAnge [⌫]",
	"➤ DeAng [⌫]",
	"➤ DeAn [⌫]",
	"➤ DeA [⌫]",
	"➤ De [⌫]",
	"➤ D [⌫]",
	"➤  [⌫]",
	"➤ |",
	"➤ ",
	"➤ |",
	"➤ ",
];
let currentTitleIndex = 0;
function updateTitle() {
	document.title = titles[currentTitleIndex];
	currentTitleIndex = (currentTitleIndex + 1) % titles.length;
}
// Title Update
setInterval(updateTitle, 100);