{
  "name": "render-curl-example",
  "version": "1.0.0",
  "description": "A simple example for Render.com",
  "main": "server.js",
  "scripts": {
    "start": "node server.js"
  },
  "dependencies": {
    "express": "^4.17.1"
  }
}
